# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 12:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=200)),
                ('news_text', models.CharField(max_length=200)),
                ('news_video_url', models.CharField(max_length=200)),
                ('news_textt', models.IntegerField(default=0)),
                ('news_fb_url', models.CharField(max_length=200)),
                ('news_twiter_url', models.CharField(max_length=200)),
                ('news_youtube_url', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
