# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 05:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0002_auto_20160410_1205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='news_textt',
        ),
    ]
