# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0004_auto_20160415_0631'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='video_url',
            new_name='newsvideourl',
        ),
    ]
