# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 07:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0005_auto_20160415_0636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='youtubeurl',
            field=models.CharField(max_length=200),
        ),
    ]
