# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 11:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0007_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail',
            name='registration',
        ),
        migrations.DeleteModel(
            name='Detail',
        ),
    ]
