# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialapp', '0008_auto_20160419_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.FileField(default=1, upload_to='static/images'),
            preserve_default=False,
        ),
    ]
